default:
  adapter: mysql2
  database: superstars
  username: sinatra
  password: w0rk5pac3
  host: localhost
development:
  adapter: mysql2
  database: superstars
  username: sinatra
  password: w0rk5pac3
  host: localhost
production:
  adapter: mysql2
  database: superstars
  username: sinatra
  password: w0rk5pac3
  host: localhost